PictureShare!/Models/PictureViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PictureShare_.Models
{
    public class PictureViewModel
    {
        public PictureModel Picture { get; set; }

        public IEnumerable<SelectListItem> CategoryList { get; set; }
    }
}

PictureShare!/Controllers/PictureController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PictureShare_.Data;
using PictureShare_.Helpers;
using PictureShare_.Models;

namespace PictureShare_.Controllers
{
    [Authorize]
    public class PictureController : Controller
    {
        private readonly ApplicationDbContext _db;
        private Images _image;
        private IWebHostEnvironment _env;
        private readonly UserManager<IdentityUser> _user;
        public PictureController(ApplicationDbContext db, Images image, IWebHostEnvironment env, UserManager<IdentityUser> user)
        {
            _db = db;
            _image = image;
            _env = env;
            _user = user;
        }

        public async Task<IActionResult> Index()
        {
            var pictures = await _db.Pictures.Where(x => x.UserEmail == User.Identity.Name).Include("Category").ToListAsync();

            foreach (var picture in pictures)
            {
                picture.Comments = await _db.Comments.Where(x => x.PictureId == picture.Id).Include("User").ToListAsync();
            }

            return View(pictures);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return View(nameof(Index));
            }

            var picture = await _db.Pictures.Where(x => x.Id.ToString() == id).Include("Category").FirstOrDefaultAsync();
            picture.Comments = await _db.Comments.Where(x => x.PictureId == picture.Id).Include("User").OrderByDescending(x => x.Timestamp).ToListAsync();
            if (picture == null)
                return View(nameof(Index));

            return View(picture);

        }

        [HttpPost]
        public async Task<IActionResult> AddComment(string comment, Guid id)
        {
            var pic =  await _db.Pictures.Where(x => x.Id == id).FirstOrDefaultAsync();
            pic.Comments.Add(new CommentModel
            {
                Comment = comment,
                PictureId = id,
                Timestamp = DateTime.Now,
                User = await _user.FindByEmailAsync(User.Identity.Name)
            }); 

            _db.Pictures.Update(pic);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = pic.Id });
        }

        [HttpGet]
        public IActionResult Create()
        {
            PictureViewModel pictureViewModel = new PictureViewModel()
            {
                Picture = new PictureModel(),
                CategoryList = _db.Categories.Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString() 
                })
            };

            return View(pictureViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PictureViewModel model)
        {
            model.Picture.TimeStamp = DateTime.Now;
            model.Picture.UserEmail = User.Identity.Name;
            model.Picture.Public = false;
            var file = Request.Form.Files[0];

            Images images = new Images(_env);
            model.Picture.ImagePath = await images.Upload(file, "/Images/");

            await _db.Pictures.AddAsync(model.Picture);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            
        }

        public async Task<IActionResult> Delete(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var model = await _db.Pictures.FirstOrDefaultAsync(x => x.Id == Guid.Parse(id));

            if (model == null)
            {
                return NotFound();
            }

            _db.Pictures.Remove(model);
            await _db.SaveChangesAsync();
            _image.Delete(model.ImagePath);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> makePublic(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _db.Pictures.FirstOrDefaultAsync(x => x.Id == id);

            if (model == null)
            {
                return NotFound();
            }

            model.Public = !model.Public;
            _db.Pictures.Update(model);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

PictureShare!/Views/Picture/Create.cshtml
@model PictureViewModel

<div class="d-flex flex-column justify-content-center align-items-center vh-85">
    <div class="card w-75 br-0 p-3">

        <form id="upload" name="upload" method="post" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <h2 class="text-center mb-3"> Upload a new picture!</h2>

            <div class="mb-3">
                <input asp-for="Picture.Caption" class="form-control form-control" type="text" placeholder="caption">
                <span asp-validation-for="Picture.Caption" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <input class="form-control" type="file" id="formFile" name="formFile" accept="image/*">
            </div>

            <div class="mb-3">
                @Html.DropDownListFor(m => m.Picture.CategoryId, Model.CategoryList, "Select a category", new {@class = "form-select"})
                 <span asp-validation-for="Picture.CategoryId" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary w-100">Upload</button>
            </div>

        </form>

    </div>
</div>

PictureShare!/Views/Picture/Details.cshtml
@model PictureModel

  <div class="row justify-content-center">
        <div class="card my-3 mx-3 shadow align-content-center align-items-center " style="width: 40rem;">
            <img src="@Model.ImagePath" class="card-img-top my-2" alt="@Model.Caption">
            <hr />
            <div class="card-body p-1 text-center">
                <h4 class="card-title fw-bold caption">@Model.Caption</h4>
                <p class="my-1 lh-1 small fst-italic">@Model.Category.Name</p>
                    <p class="my-1 lh-1 small fst-italic">@Model.UserEmail</p>
                    <p class="my-1 lh-1 small fst-italic">@Model.TimeStamp</p>
                </div>
        </div>
   </div>

   <div class="row mt-5">
    <div class="col">
        <form asp-action="AddComment" method="post">
            <input type="hidden" value="@Model.Id" name="id" />
            <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="Type here..." name="comment" />
              <button type="submit" class="btn btn-outline-secondary">Add Comment</button>
            </div>
        </form>
    </div>
   </div>

   @foreach (var comment in @Model.Comments)
   {
        <div class="alert alert-primary" role="alert">
           @comment.Comment
           <br />
           <p class="my-1 lh-1 small fst-italic">@comment.Timestamp by @comment.User.UserName</p>
        </div>
   }
      

PictureShare!/Views/Picture/Index.cshtml
@model IEnumerable<PictureModel>

@if (Model != null)
{
        <div class="row">
        @foreach (var item in Model)
        {
                    <div class="card my-3 mx-3 shadow" style="width: 18rem;">
                        <a class="ms-auto text-decoration-none" asp-controller="Picture" asp-action="Delete" asp-route-id="@item.Id">X</a>
                        <img src="@item.ImagePath" class="card-img-top my-2" alt="@item.Caption">

                        <hr />
                        <div class="card-body p-1 text-center">
                            <h4 class="card-title fw-bold caption">@item.Caption</h4>
                            <p class="my-1 lh-1 small fst-italic">@item.Category.Name</p>
                             <p class="my-1 lh-1 small fst-italic">@item.UserEmail</p>
                             <p class="my-1 lh-1 small fst-italic">@item.TimeStamp</p>
                             <a class="btn btn-primary" asp-action="makePublic" asp-route-id="@item.Id">@( item.Public ? "Make Private" : "Make Public" )</a>
                             <p class="my-1 lh-1 small fst-italic">@item.Comments.Count() comments</p>
                             <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.Id">Add Comment</a>
                         </div>
                    </div>
           
        } 
        </div>
}